### ISSUE TITLE
There are some problems in the model.

### ISSUE THREAD

**Issue by wendychengdu** [ironfist2/Authorship-Attribution-of-Short-Texts#1]
Hi, I tried to run the model-1 and eventually got an accuracy of closing to 90%, but the accuracy for  each step were higher than the average accuracy in each epoch ,which was very strange. Then I tried to run the model-2 (using character embedding) but I just got an accuracy of nearly 4%, which was a random probability (there are 22 authors, 1/22=0.045). So this is an invalid model. Do you know the problem? I don't know how to solve it. I hope to get your advice. Thank you!

**Comment by jan-stas** [comment]
Hi, i would like to inform you, there is any documentation for this project, any paper or tutorial?
Thank you!
Jan

**Comment by ironfist2** [comment]
Hi, this implementation is based on the paper titled "Convolutional Neural Networks for Authorship Attribution of Short Texts"

**Comment by luisfredgs** [comment]
Hello @ironfist2. Are you the paper author? This is the official implementation??

**Comment by ironfist2** [comment]
No I am not the author. Nether this is the official implementation. Its just my own implementation of the paper

**Comment by Rkrohit371** [comment]
Traceback (most recent call last):
  File "main.py", line 56, in <module>
    nb_filter, cat_output)
  File "/home/rohit/Authorship-Attribution-of-Short-Texts/predict_def.py", line 29, in model
    input_shape=(maxlen, vocab_size))(inputs)
TypeError: __init__() missing 2 required positional arguments: 'filters' and 'kernel_size'


Please tell me, how to remove this error?

**Comment by salhasalman** [comment]
@luisfredgs @ironfist2 @wendychengdu @jan-stas 
does anyone know the numpy sklearn keras pandas version of the code used

**Comment by salhasalman** [comment]
@wendychengdu @ironfist2 I also noticed that accuracy of each step in epoch is higher than average accuracy is that a problem with the model?
